
const forceLogin=new URLSearchParams(location.search).get('login')==='1';if(forceLogin)localStorage.removeItem('hmi_admin_token');
const token=()=>localStorage.getItem('hmi_admin_token');const $=id=>document.getElementById(id);
async function logout(){try{await fetch('/api/auth/logout',{method:'POST',credentials:'same-origin'})}finally{localStorage.removeItem('hmi_admin_token');location.href='admin.html?login=1'}}
async function login(){const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('user').value,password:$('pass').value})});const d=await r.json();if(!r.ok){$('loginMsg').textContent=d.message;return}localStorage.removeItem('hmi_admin_token');history.replaceState({},'', 'admin.html');show()}
async function show(){try{const r=await fetch('/api/admin/stats',{credentials:'same-origin'});if(!r.ok)return;$('loginBox').classList.add('hidden');$('panel').classList.remove('hidden');loadAll()}catch(e){}}
async function api(url,opt={}){opt.credentials='same-origin';opt.headers={...(opt.headers||{})};if(opt.body&&typeof opt.body!=='string')opt.body=JSON.stringify(opt.body);if(opt.body)opt.headers['Content-Type']='application/json';const r=await fetch(url,opt);if(r.status===401){logout();throw new Error('Sesi admin berakhir. Silakan login kembali.')}const d=await r.json();if(!r.ok)throw new Error(d.message||'Terjadi kesalahan');return d}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function loadAll(){await loadStats();await loadApplicants();await loadKader();await loadRejected()}
async function loadStats(){const s=await api('/api/admin/stats');Object.keys(s).forEach(k=>$(k)&&($(k).textContent=s[k]))}
async function loadApplicants(){try{const p=new URLSearchParams({q:$('q').value,status:$('status').value});const data=await api('/api/admin/applicants?'+p);$('rows').innerHTML=data.map(a=>`<tr><td>${esc(a.registration_no)}</td><td><b>${esc(a.nama)}</b><br><small>${esc(a.wa)}</small></td><td>${esc(a.prodi)}</td><td>${esc(a.angkatan)}</td><td><span class="badge">${esc(a.status)}</span></td><td><button class="btn2" onclick="detailApplicant(${a.id})">👁️ Detail</button> <button class="btn2" onclick="setStatus(${a.id},'Verifikasi')">Verifikasi</button> <button class="btn2" onclick="setStatus(${a.id},'Diterima')">✅ Terima</button> <button class="btn2 danger" onclick="setStatus(${a.id},'Ditolak')">❌ Tolak</button></td></tr>`).join('')||'<tr><td colspan="6">Belum ada data.</td></tr>';await loadStats()}catch(e){alert(e.message)}}
async function setStatus(id,st){const note=prompt(st==='Ditolak'?'Alasan/catatan penolakan (opsional):':'Catatan admin (opsional):','');if(note===null)return;try{const d=await api('/api/admin/applicants/'+id+'/status',{method:'PATCH',body:{status:st,admin_note:note}});alert(d.message);await loadAll()}catch(e){alert(e.message)}}
async function detailApplicant(id){try{const a=await api('/api/admin/applicants/'+id);const photo=a.photo?`<img src="/api/admin/applicants/${a.id}/photo" alt="Foto">`:'<div>Tidak ada foto</div>';$('modalTitle').textContent='Detail Pendaftar';$('detail').innerHTML=photo+`<b>Nomor Pendaftaran</b><span>${esc(a.registration_no)}</span><b>Nama</b><span>${esc(a.nama)}</span><b>WhatsApp</b><span>${esc(a.wa)}</span><b>Program Studi</b><span>${esc(a.prodi)}</span><b>Angkatan</b><span>${esc(a.angkatan)}</span><b>Alasan</b><span>${esc(a.alasan)}</span><b>Status</b><span>${esc(a.status)}</span><b>Catatan Admin</b><span>${esc(a.admin_note||'-')}</span>`;$('wordBtn').onclick=()=>download('/api/admin/applicants/'+id+'/word');$('photoBtn').onclick=()=>download('/api/admin/applicants/'+id+'/photo');$('pdfBtn').onclick=()=>openPrint(id);$('modal').classList.remove('hidden')}catch(e){alert(e.message)}}
function closeModal(){$('modal').classList.add('hidden')}
async function download(url){try{const r=await fetch(url,{credentials:'same-origin'});if(!r.ok)throw new Error('Gagal mengunduh file');const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(r.headers.get('Content-Disposition')||'').match(/filename="?([^";]+)"?/i)?.[1]||'download';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert(e.message)}}
function openPrint(id){window.open('/api/admin/applicants/'+id+'/print','_blank','noopener')}
async function exportFile(url,name){try{const r=await fetch(url,{credentials:'same-origin'});if(!r.ok)throw new Error('Gagal membuat file Excel');const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert(e.message)}}
function switchTab(tab){
  ['penerimaan','kader','cms','rejected'].forEach(x=>$(x).classList.toggle('hidden',x!==tab));
  ['tabPenerimaan','tabKader','tabCms','tabRejected'].forEach(x=>$(x).classList.remove('active'));
  const tabId={penerimaan:'tabPenerimaan',kader:'tabKader',cms:'tabCms',rejected:'tabRejected'}[tab];
  if(tabId) $(tabId).classList.add('active');
  if(tab==='kader') loadKader();
  if(tab==='rejected') loadRejected();
  if(tab==='cms') loadCMSAdmin();
}
async function loadRejected(){try{const data=await api('/api/admin/rejected');$('rejectedRows').innerHTML=data.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.nama)}</td><td>${esc(r.registration_no)}</td><td>${esc(r.prodi)}</td><td>${esc(r.angkatan)}</td><td>${new Date(r.rejected_at).toLocaleString('id-ID')}</td><td><button class="btn2" onclick="detailApplicant(${r.applicant_id})">Lihat</button></td></tr>`).join('')||'<tr><td colspan="7">Belum ada riwayat ditolak.</td></tr>'}catch(e){alert(e.message)}}
async function loadKader(){try{const p=new URLSearchParams({q:$('kq').value,status:$('kstatus').value,angkatan:$('kangkatan').value});const data=await api('/api/admin/kader?'+p);const years=[...new Set(data.map(k=>String(k.angkatan||'')).filter(Boolean))].sort();const old=$('kangkatan').value;$('kangkatan').innerHTML='<option value="semua">Semua Angkatan</option>'+years.map(y=>`<option value="${esc(y)}">${esc(y)}</option>`).join('');$('kangkatan').value=years.includes(old)?old:'semua';$('kaderRows').innerHTML=data.map((k,i)=>`<tr><td>${i+1}</td><td>${esc(k.nama)}</td><td>${esc(k.nim)}</td><td>${esc(k.prodi)}</td><td>${esc(k.angkatan)}</td><td>${esc(k.status)}</td><td><button class="btn2" onclick="lihatKader(${k.id})">👁️ Lihat</button> <button class="btn2" onclick="editKader(${k.id})">Edit</button> <button class="btn2 danger" onclick="hapusKader(${k.id})">Hapus</button></td></tr>`).join('')||'<tr><td colspan="7">Belum ada data kader.</td></tr>'}catch(e){alert(e.message)}}
async function lihatKader(id){try{const k=await api('/api/admin/kader/'+id);const foto=k.foto?`<img src="/api/admin/kader/${id}/photo" alt="Foto kader">`:'<div>Tidak ada foto</div>';$('modalTitle').textContent='Data Kader';$('detail').innerHTML=foto+`<b>Nama</b><span>${esc(k.nama)}</span><b>NIM</b><span>${esc(k.nim||'-')}</span><b>Prodi</b><span>${esc(k.prodi||'-')}</span><b>Angkatan</b><span>${esc(k.angkatan||'-')}</span><b>Status</b><span>${esc(k.status||'-')}</span><b>WhatsApp</b><span>${esc(k.wa||'-')}</span><b>Fakultas</b><span>${esc(k.fakultas||'-')}</span><b>Kampus</b><span>${esc(k.kampus||'-')}</span><b>Jabatan</b><span>${esc(k.jabatan||'-')}</span><b>Keterangan</b><span>${esc(k.keterangan||'-')}</span>`;$('wordBtn').style.display='none';$('pdfBtn').onclick=()=>window.print();$('photoBtn').onclick=()=>download('/api/admin/kader/'+id+'/photo');$('modal').classList.remove('hidden')}catch(e){alert(e.message)}}
function resetModalButtons(){$('wordBtn').style.display='inline-block'}
function openForm(k={}){$('kaderModal').classList.remove('hidden');$('formTitle').textContent=k.id?'Edit Kader':'Tambah Kader';$('formMsg').textContent='';const map={kid:'id',nama:'nama',nim:'nim',prodi:'prodi',angkatan:'angkatan',tahun_masuk:'tahun_masuk',kstatusForm:'status',kampus:'kampus',fakultas:'fakultas',lk1:'lk1',lk2:'lk2',lk3:'lk3',jabatan:'jabatan',periode:'periode',email:'email',wa:'wa',keterangan:'keterangan'};Object.keys(map).forEach(id=>$(id).value=k[map[id]]??(id==='kstatusForm'?'Aktif':''))}
function closeKaderForm(){$('kaderModal').classList.add('hidden')}
async function editKader(id){try{openForm(await api('/api/admin/kader/'+id))}catch(e){alert(e.message)}}
async function hapusKader(id){if(!confirm('Hapus data kader ini?'))return;try{alert((await api('/api/admin/kader/'+id,{method:'DELETE'})).message);await loadAll()}catch(e){alert(e.message)}}
$('form').addEventListener('submit',async e=>{e.preventDefault();$('formMsg').textContent='Menyimpan...';const obj={};['nama','nim','prodi','angkatan','tahun_masuk','kampus','fakultas','lk1','lk2','lk3','jabatan','periode','email','wa','keterangan'].forEach(f=>obj[f]=$(f).value.trim());obj.status=$('kstatusForm').value;try{const id=$('kid').value;const d=await api(id?'/api/admin/kader/'+id:'/api/admin/kader',{method:id?'PUT':'POST',body:obj});alert(d.message);closeKaderForm();await loadAll()}catch(e){$('formMsg').textContent=e.message}})
$('q').oninput=loadApplicants;$('status').onchange=loadApplicants;$('kq').oninput=loadKader;$('kstatus').onchange=loadKader;$('kangkatan').onchange=loadKader;
let cmsCache={}; let cmsTab='berita'; let cmsEditing=null;
async function loadCMSAdmin(){try{cmsCache=await api('/api/cms');cmsOpen(cmsTab)}catch(e){alert(e.message)}}
function cmsOpen(key,edit=null){cmsTab=key;cmsEditing=edit;document.querySelectorAll('.cms-btn').forEach(b=>b.classList.toggle('active',b.textContent.toLowerCase().includes(key==='profil'?'profil':key)));const e=$('cmsEditor');if(key==='profil')return e.innerHTML=`<div class="cms-form"><label>Judul Website<input id="siteTitle"></label><label>Deskripsi<input id="siteDescription"></label><label>Hero Title<input id="heroTitle"></label><label>Hero Text<input id="heroText"></label><label>WhatsApp<input id="contactWhatsapp" placeholder="62812..."></label><label>Instagram<input id="contactInstagram"></label><label>Email<input id="contactEmail"></label><label>Alamat<input id="contactAddress"></label><label class="full">Background Website<input id="siteBackground" placeholder="assets/background.jpg"></label><div class="full"><input id="bgFile" type="file" accept="image/jpeg,image/png,image/webp"><button class="btn" onclick="uploadBackground()">⬆️ Upload Background</button></div><label class="full">Sejarah<textarea id="aboutSejarah" rows="5"></textarea></label><label>Visi<textarea id="aboutVisi" rows="4"></textarea></label><label>Misi<textarea id="aboutMisi" rows="4"></textarea></label><div class="full"><button class="btn" onclick="saveProfile()">💾 Simpan Profil & Kontak</button></div></div>`,fillProfile();
const cfg={berita:{title:'Berita',fields:[['judul','Judul'],['tanggal','Tanggal'],['kategori','Kategori'],['ringkas','Ringkasan'],['isi','Isi Berita'],['gambar','URL/hasil upload foto'],['status','Status']],status:['Draft','Publikasi']},galeri:{title:'Galeri',fields:[['judul','Judul Kegiatan'],['tanggal','Tanggal'],['gambar','URL/hasil upload foto'],['deskripsi','Deskripsi']]},agenda:{title:'Agenda',fields:[['tanggal','Tanggal'],['judul','Nama Kegiatan'],['lokasi','Lokasi'],['keterangan','Keterangan'],['status','Status']],status:['Akan Datang','Berlangsung','Selesai']},struktur:{title:'Struktur',fields:[['nama','Nama'],['jabatan','Jabatan'],['periode','Periode'],['foto','URL/hasil upload foto']]}};const x=cfg[key];e.innerHTML=`<h3>${x.title}</h3><div class="cms-form">${x.fields.map(([id,l])=>x.status&&id==='status'?`<label>${l}<select id="f_${id}">${x.status.map(v=>`<option>${v}</option>`).join('')}</select></label>`:`<label>${l}<input id="f_${id}"></label>`).join('')}<div class="full"><input id="cmsFile" type="file" accept="image/jpeg,image/png,image/webp"><button class="btn" onclick="uploadCmsImage()">⬆️ Upload Foto</button><span id="uploadMsg" class="muted"></span></div><div class="full"><button class="btn" onclick="cmsSave('${key}')">💾 Tambah ${x.title}</button></div></div><div id="cmsList" class="cms-list"></div>`;cmsRenderList(key);}
async function uploadCmsImage(){const f=$('cmsFile').files[0];if(!f)return alert('Pilih foto terlebih dahulu.');const fd=new FormData();fd.append('image',f);const r=await fetch('/api/admin/cms/upload',{method:'POST',body:fd,credentials:'same-origin'});const d=await r.json();if(!r.ok)return alert(d.message||'Upload gagal');if($('f_gambar')) $('f_gambar').value=d.url;if($('f_foto')) $('f_foto').value=d.url;$('uploadMsg').textContent=' Upload berhasil';}
async function cmsSave(key){const fields={berita:['judul','tanggal','kategori','ringkas','isi','gambar','status'],galeri:['judul','tanggal','gambar','deskripsi'],agenda:['tanggal','judul','lokasi','keterangan','status'],struktur:['nama','jabatan','periode','foto']}[key];const obj={};fields.forEach(f=>obj[f]=($('f_'+f)?.value||'').trim());if(!obj.judul&&key!=='struktur' || key==='struktur'&&!obj.nama)return alert('Isi data utama terlebih dahulu.');try{await api('/api/admin/cms/'+key+(cmsEditing?'/'+cmsEditing.id:''),{method:cmsEditing?'PUT':'POST',body:obj});alert(cmsEditing?'Perubahan disimpan.':'Berhasil disimpan.');cmsCache=await api('/api/cms');cmsOpen(key)}catch(e){alert(e.message)}}
function cmsEdit(key,id){const x=(cmsCache[key]||[]).find(v=>Number(v.id)===Number(id));if(!x)return;cmsOpen(key,x);setTimeout(()=>{Object.keys(x).forEach(f=>{if($('f_'+f))$('f_'+f).value=x[f]||''});const b=document.querySelector('#cmsEditor .btn');if(b)b.textContent='💾 Simpan Perubahan'},0)}
async function cmsDelete(key,id){if(!confirm('Hapus konten ini?'))return;try{await api('/api/admin/cms/'+key+'/'+id,{method:'DELETE'});cmsCache=await api('/api/cms');cmsOpen(key)}catch(e){alert(e.message)}}
function cmsRenderList(key){const arr=cmsCache[key]||[];const title=key==='struktur'?'nama':'judul';$('cmsList').innerHTML=arr.map(x=>`<div class="cms-item"><div>${(x.gambar||x.foto)?`<img src="${esc(x.gambar||x.foto)}" loading="lazy">`:''}<b>${esc(x[title]||'(tanpa judul)')}</b><br><small>${esc(x.tanggal||x.periode||x.status||'')}</small></div><div class="cms-actions"><button class="btn2" onclick="cmsEdit('${key}',${x.id})">Edit</button><button class="btn2 danger" onclick="cmsDelete('${key}',${x.id})">Hapus</button></div></div>`).join('')||'<p class="muted">Belum ada data.</p>'}
function fillProfile(){const c=cmsCache;const s=c.site||{},t=c.tentang||{};['siteTitle','siteDescription','heroTitle','heroText','contactWhatsapp','contactInstagram','contactEmail','contactAddress','siteBackground'].forEach(id=>$(id).value=s[{siteTitle:'title',siteDescription:'description',heroTitle:'heroTitle',heroText:'heroText',contactWhatsapp:'contactWhatsapp',contactInstagram:'contactInstagram',contactEmail:'contactEmail',contactAddress:'contactAddress'}[id]]||'');$('aboutSejarah').value=t.sejarah||'';$('aboutVisi').value=t.visi||'';$('aboutMisi').value=t.misi||''}
async function uploadBackground(){const f=$('bgFile').files[0];if(!f)return alert('Pilih gambar background.');const fd=new FormData();fd.append('image',f);const r=await fetch('/api/admin/cms/upload',{method:'POST',body:fd,credentials:'same-origin'});const d=await r.json();if(!r.ok)return alert(d.message||'Upload gagal');$('siteBackground').value=d.url;alert('Background berhasil diunggah.');}
async function saveProfile(){try{await api('/api/admin/cms/site',{method:'PUT',body:{title:$('siteTitle').value,description:$('siteDescription').value,heroTitle:$('heroTitle').value,heroText:$('heroText').value,contactWhatsapp:$('contactWhatsapp').value,contactInstagram:$('contactInstagram').value,contactEmail:$('contactEmail').value,contactAddress:$('contactAddress').value,background:$('siteBackground').value}});await api('/api/admin/cms/tentang',{method:'PUT',body:{sejarah:$('aboutSejarah').value,visi:$('aboutVisi').value,misi:$('aboutMisi').value}});alert('Profil & kontak tersimpan.');loadCMSAdmin()}catch(e){alert(e.message)}}
show();
