(function(){
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const setText=(sel,v)=>document.querySelectorAll(sel).forEach(e=>{if(v)e.textContent=v});
async function loadCMS(){try{const r=await fetch('/api/cms',{cache:'no-store'});if(!r.ok)return;const c=await r.json();
 const site=c.site||{}; setText('[data-cms-hero-title]',site.heroTitle); setText('[data-cms-hero-text]',site.heroText); setText('[data-cms-description]',site.description); setText('[data-cms-site-title]',site.title); setText('[data-cms-footer]',site.footerText); setText('[data-cms-copyright]',site.copyright); setText('[data-cms-home-welcome-title]',site.homeWelcomeTitle); setText('[data-cms-home-welcome-text]',site.homeWelcomeText); setText('[data-cms-home-quote]',site.homeQuote); setText('[data-cms-home-quote-text]',site.homeQuoteText);
 const bg=site.background;if(bg)document.querySelectorAll('.home-hero,.page-hero').forEach(e=>e.style.backgroundImage=`url("${esc(bg)}")`);
 const pageKey=document.body.dataset.cmsPage; const pg=c.pages?.[pageKey]; if(pg){
  document.querySelectorAll('[data-cms-page-title]').forEach(e=>e.textContent=String(pg.title??''));
  document.querySelectorAll('[data-cms-page-intro]').forEach(e=>e.textContent=String(pg.intro??''));
  document.querySelectorAll('[data-cms-page-body]').forEach(e=>{const body=String(pg.body??'').trim();e.innerHTML=body?body.split(/\n\s*\n/).map(part=>`<p>${esc(part).replace(/\n/g,'<br>')}</p>`).join(''):''});
  document.querySelectorAll('[data-cms-page-link]').forEach(e=>{const link=String(pg.link??'').trim(); if(link){e.href=link;e.textContent=String(pg.linkLabel||'Buka Materi');e.classList.remove('hidden')}else{e.removeAttribute('href');e.textContent='';e.classList.add('hidden')}});
}
 const news=document.querySelector('[data-cms-list="berita"]');if(news)news.innerHTML=(c.berita||[]).filter(x=>!x.status||x.status==='Publikasi').map(x=>`<article class="card"><img src="${esc(x.gambar||'/background.jpg')}" alt="${esc(x.judul)}" loading="lazy"><div><span class="tag">${esc(x.kategori)}</span><h3>${esc(x.judul)}</h3><small>${esc(x.tanggal)}</small><p>${esc(x.ringkas)}</p></div></article>`).join('')||'<p>Belum ada berita.</p>';
 const gal=document.querySelector('[data-cms-list="galeri"]');if(gal)gal.innerHTML=(c.galeri||[]).map(x=>`<figure><img src="${esc(x.gambar||'/background.jpg')}" alt="${esc(x.judul)}" loading="lazy"><figcaption>${esc(x.judul)}</figcaption></figure>`).join('')||'<p>Belum ada galeri.</p>';
 const ag=document.querySelector('[data-cms-list="agenda"]');if(ag)ag.innerHTML=(c.agenda||[]).map(x=>`<article class="agenda-item"><div class="date">${esc(x.tanggal)}</div><div><span class="tag">${esc(x.status||'AGENDA')}</span><h3>${esc(x.judul)}</h3><p>${esc(x.lokasi)}</p><p>${esc(x.keterangan)}</p></div></article>`).join('')||'<p>Belum ada agenda.</p>';
 const about=c.tentang||{};setText('[data-cms="sejarah"]',about.sejarah);setText('[data-cms="visi"]',about.visi);setText('[data-cms="misi"]',about.misi);
 const st=document.querySelector('[data-cms-list="struktur"]');if(st){let arr=(c.struktur||[]).filter(x=>String(x.tampil||'Ya')!=='Tidak').sort((a,b)=>(Number(a.urutan)||9999)-(Number(b.urutan)||9999));st.innerHTML=arr.map(x=>`<div class="person"><img src="${esc(x.foto||'/hmi.png')}" alt="${esc(x.nama)}" loading="lazy"><h3>${esc(x.nama)}</h3><p>${esc(x.jabatan)}</p><small>${esc(x.periode)}${x.bagian?' • '+esc(x.bagian):''}</small></div>`).join('')||'<p>Struktur belum diperbarui.</p>';}
 const map={wa:site.contactWhatsapp,ig:site.contactInstagram,email:site.contactEmail,address:site.contactAddress};Object.entries(map).forEach(([k,v])=>document.querySelectorAll(`[data-cms-contact="${k}"]`).forEach(e=>{if(v)e.textContent=v;if(e.tagName==='A'&&v)e.href=k==='wa'?'https://wa.me/'+v.replace(/\D/g,''):v}));
}catch(e){console.warn('CMS:',e)}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',loadCMS);else loadCMS();})();